### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by ghuniyu** [BinarCode/laravel-nova-chat#5]
is this me wrong on setup or this project not done yet?

![nothing](https://user-images.githubusercontent.com/20877422/82113617-a307e380-9781-11ea-9100-3e0fbc37b9ce.png)

it shows blank

**Comment by xoco70** [comment]
+1

**Comment by xoco70** [comment]
I think it is because of this error:

```
[previous excepo [object] (PDOException(code: 42501): SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for table users at /home/jo/Code/acc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)
[stacktrace]
#0 /home/jo/Code/acc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(127): PDOStatement->execute()
#1 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(335): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#3 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#4 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#5 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select()
#6 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#7 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#8 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#9 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(537): Illuminate\\Database\\Query\\Builder->get()
#10 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Eloquent\\Builder->getModels()
#11 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get()
#12 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(52): Illuminate\\Database\\Eloquent\\Builder->first()
#13 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(139): Illuminate\\Auth\\EloquentUserProvider->retrieveById()
#14 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\SessionGuard->user()
#15 /home/jo/Code/acc/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(62
```
